name: 'NPM Publish'
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publishing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build on node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - run: yarn test:cover
        env:
          CI: true

      - name: GitHub Test on Slack
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@1.6.2
        with:
          args: 'Resistor build has been tested, now queues for build if needed'

      - name: Publish if version has been updated
        if: success()
        uses: pascalgn/npm-publish-action@1.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
