name: 'Publish'
on:
  push:
    branches:
      - main
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build in testing mode
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - run: yarn test:cover

      - name: Export coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs: testing
    if: success()

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build in production mode
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build:prod

      - name: NPM publish
        uses: pascalgn/npm-publish-action@1.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: GPM publish
        if: success()
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@hisorange'
      - run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-success:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: publish
    if: success()

    steps:
      - name: Notify the authors
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Circuit Actions
          SLACK_AVATAR: repository
        with:
          args: 'New version has been released!'


  notify-error:
    name: Notify Error
    runs-on: ubuntu-latest
    needs: testing
    if: failure()

    steps:
      - name: Notify the authors
        uses: Ilshidur/action-slack@2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Circuit Actions
          SLACK_AVATAR: repository
        with:
          args: 'Tests are failing!'

